local_backend: true

backend:
  name: git-gateway
  branch: main

display_url: http://localhost:1313
site_url: https://www.maistra.com/
media_folder: /static/media
public_folder: /media

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields: [
      {name: title, widget: string},
      {name: body, widget: markdown},
    ]

  - name: pages
    label: Pages
    files: [
      {name: index, label: Index, file: content/_index.md, fields: [
        {name: title, widget: string},
      {name: body, widget: markdown},
      ]},
      {name: about, label: About, file: content/about.md, fields: [
        {name: title, widget: string},
        {name: body, widget: markdown},
      ]},
    ]
